apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-db-deployment
  labels:
   type: restapi
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: flask-db
  replicas: 3
  template:
    metadata:
      name: flask-db-tmpl
      labels:
        app: flask-db
    spec:
      containers:
      - name: my-flsak-db-pg 
        image: my-flsak-db-pg:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 45612
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: flask-db-deployment
                key: host
          - name: POSTGRES_DATABASE
            valueFrom: 
              secretKeyRef: 
                name: flask-db-deployment
                key: database
          - name: POSTGRES_USERNAME
            valueFrom: 
              secretKeyRef: 
                name: flask-db-deployment
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: flask-db-deployment
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: flask-db-service
spec:
  type: NodePort
  selector:
    app: flask-db
  ports:
   - protocol: "TCP"
     port: 80
     targetPort: 45612
